In [1]:
import requests
import pandas as pd
import os

from dotenv import load_dotenv

load_dotenv()

APP_ID = os.getenv("ADZUNA_APP_ID")
APP_KEY = os.getenv("ADZUNA_APP_KEY")

In [2]:
print(APP_ID is not None)
print(APP_KEY is not None)

True
True

In [3]:
country = "in"
page = 1

url = f"https://api.adzuna.com/v1/api/jobs/{country}/search/{page}"

params = {
    "app_id": APP_ID,
    "app_key": APP_KEY,
    "results_per_page": 10,
    "what": "data scientist"
}

response = requests.get(url, params=params)

In [4]:
print(response.status_code)

200

In [5]:
data = response.json()

print(type(data))

<class 'dict'>

In [6]:
data.keys()

dict_keys(['count', '__CLASS__', 'mean', 'results'])

In [7]:
jobs = data["results"]

print(type(jobs))
print(len(jobs))

<class 'list'>
10

In [8]:
print(response.status_code)

200

In [9]:
data = response.json()
print(type(data))
data.keys()

<class 'dict'>

dict_keys(['count', '__CLASS__', 'mean', 'results'])

In [10]:
data = response.json()
print(type(data))
data.keys()

<class 'dict'>

dict_keys(['count', '__CLASS__', 'mean', 'results'])

In [11]:
jobs = data["results"]

print(type(jobs))
print(len(jobs))

<class 'list'>
10

In [12]:
first_job.keys()

NameError: name 'first_job' is not defined

In [13]:
first_job = jobs[0]

print(type(first_job))

<class 'dict'>

In [14]:
first_job.keys()

dict_keys(['redirect_url', '__CLASS__', 'created', 'location', 'company', 'category', 'adref', 'contract_time', 'id', 'description', 'salary_is_predicted', 'title'])

In [15]:
jobs = data["results"]
print(type(jobs))
print(len(jobs))

<class 'list'>
10

In [16]:
first_job = jobs[0]
first_job.keys()

dict_keys(['redirect_url', '__CLASS__', 'created', 'location', 'company', 'category', 'adref', 'contract_time', 'id', 'description', 'salary_is_predicted', 'title'])

In [17]:
print("Title:", first_job.get("title"))
print("Company:", first_job.get("company"))
print("Location:", first_job.get("location"))
print("Category:", first_job.get("category"))
print("Contract Time:", first_job.get("contract_time"))
print("Created:", first_job.get("created"))
print("Salary Predicted:", first_job.get("salary_is_predicted"))
print("Description:", first_job.get("description"))

Title: Data Scientist-Data Science-Data Scientist
Company: {'__CLASS__': 'Adzuna::API::Response::Company', 'display_name': 'EXL'}
Location: {'display_name': 'India', 'area': ['India'], '__CLASS__': 'Adzuna::API::Response::Location'}
Category: {'tag': 'energy-oil-gas-jobs', 'label': 'Energy, Oil & Gas Jobs', '__CLASS__': 'Adzuna::API::Response::Category'}
Contract Time: full_time
Created: 2026-02-26T01:46:48Z
Salary Predicted: 0
Description: Description Data Scientists design and implement data analysis processes to derive actionable insights. Duties include building statistical models, analyzing large datasets, and presenting findings to stakeholders. You will collaborate with other data professionals to solve complex problems and improve business outcomes. Proficiency in data science tools and techniques is essential. Responsibilities · Data collation, processing, cleaning & transformation along with feature engineering and model…

In [18]:
print("Salary Min:", first_job.get("salary_min"))
print("Salary Max:", first_job.get("salary_max"))

Salary Min: None
Salary Max: None

In [19]:
for i, job in enumerate(jobs):
    print(
        i,
        job.get("title"),
        "| Min:", job.get("salary_min"),
        "| Max:", job.get("salary_max"),
        "| Predicted:", job.get("salary_is_predicted")
    )

0 Data Scientist-Data Science-Data Scientist | Min: None | Max: None | Predicted: 0
1 Data Scientist Data Science Intern | Min: None | Max: None | Predicted: 0
2 Data Scientist Data Science Intern | Min: None | Max: None | Predicted: 0
3 Data Scientist Data Science Intern | Min: None | Max: None | Predicted: 0
4 Data Scientist Data Science Intern | Min: None | Max: None | Predicted: 0
5 Data Scientist Data Science Intern | Min: None | Max: None | Predicted: 0
6 Data Scientist Data Science Intern | Min: None | Max: None | Predicted: 0
7 Data Scientist Senior Data Scientist | Min: None | Max: None | Predicted: 0
8 Data Scientist/Senior Data Scientist | Min: None | Max: None | Predicted: 0
9 Data Scientist/Senior Data Scientist | Min: None | Max: None | Predicted: 0

In [20]:
url = "https://api.adzuna.com/v1/api/jobs/in/search/1"

params = {
    "app_id": APP_ID,
    "app_key": APP_KEY,
    "results_per_page": 50,
    "what": "software engineer",
    "salary_min": 1
}

response = requests.get(url, params=params)

print("Status code:", response.status_code)

Status code: 200

In [21]:
data = response.json()
jobs = data["results"]

print("Jobs returned:", len(jobs))

Jobs returned: 50

In [22]:
salary_jobs = [
    job for job in jobs
    if job.get("salary_min") is not None
    and job.get("salary_max") is not None
]

print("Total jobs:", len(jobs))
print("Jobs with salary:", len(salary_jobs))

Total jobs: 50
Jobs with salary: 50

In [23]:
for job in salary_jobs[:5]:
    print("Title:", job.get("title"))
    print("Location:", job.get("location", {}).get("display_name"))
    print("Salary Min:", job.get("salary_min"))
    print("Salary Max:", job.get("salary_max"))
    print("-" * 50)

Title: Software Engineering - Custom Software Engineer
Location: Hussainialam, Hyderabad
Salary Min: 1000000
Salary Max: 2700000
--------------------------------------------------
Title: Software Engineering - Custom Software Engineer
Location: Richmond Town, Bangalore
Salary Min: 1200000
Salary Max: 1650000
--------------------------------------------------
Title: Software Engineering - Custom Software Engineer
Location: Richmond Town, Bangalore
Salary Min: 1200000
Salary Max: 1399992
--------------------------------------------------
Title: Software Engineer
Location: India
Salary Min: 1500000
Salary Max: 1600000
--------------------------------------------------
Title: Software Engineer
Location: Bangalore, Karnataka
Salary Min: 100000
Salary Max: 2000000
--------------------------------------------------

In [24]:
job.get("location", {}).get("display_name")

'Bangalore, Karnataka'

In [25]:
for job in salary_jobs[:10]:
    print("Title:", job.get("title"))
    print("Location:", job.get("location", {}).get("display_name"))
    print("Salary Min:", job.get("salary_min"))
    print("Salary Max:", job.get("salary_max"))
    print("Predicted:", job.get("salary_is_predicted"))
    print("-" * 50)

Title: Software Engineering - Custom Software Engineer
Location: Hussainialam, Hyderabad
Salary Min: 1000000
Salary Max: 2700000
Predicted: 0
--------------------------------------------------
Title: Software Engineering - Custom Software Engineer
Location: Richmond Town, Bangalore
Salary Min: 1200000
Salary Max: 1650000
Predicted: 0
--------------------------------------------------
Title: Software Engineering - Custom Software Engineer
Location: Richmond Town, Bangalore
Salary Min: 1200000
Salary Max: 1399992
Predicted: 0
--------------------------------------------------
Title: Software Engineer
Location: India
Salary Min: 1500000
Salary Max: 1600000
Predicted: 0
--------------------------------------------------
Title: Software Engineer
Location: Bangalore, Karnataka
Salary Min: 100000
Salary Max: 2000000
Predicted: 0
--------------------------------------------------
Title: Software Engineer / Senior Software Engineer
Location: Hyderabad, Telangana
Salary Min: 100000
Salary Max: 1500000
Predicted: 0
--------------------------------------------------
Title: Software Engineer/Sr Software Engineer
Location: India
Salary Min: 1400000
Salary Max: 1500000
Predicted: 0
--------------------------------------------------
Title: Software Engineer/ Senior Software Engineer
Location: Bangalore, Karnataka
Salary Min: 500000
Salary Max: 1500000
Predicted: 0
--------------------------------------------------
Title: Software Engineer/Senior Software Engineer
Location: Bangalore, Karnataka
Salary Min: 800000
Salary Max: 2500000
Predicted: 0
--------------------------------------------------
Title: Software Engineer/Sr.Software Engineer
Location: India
Salary Min: 300000
Salary Max: 1500000
Predicted: 0
--------------------------------------------------

In [26]:
df = pd.DataFrame(salary_jobs)

df.head()

,latitude,location,created,__CLASS__,company,redirect_url,title,salary_min,salary_max,id,category,description,adref,salary_is_predicted,longitude,contract_time,contract_type
0,17.37908,{'__CLASS__': 'Adzuna::API::Response::Location...,2026-10-05T23:54:21Z,Adzuna::API::Response::Job,{'__CLASS__': 'Adzuna::API::Response::Company'...,https://www.adzuna.in/details/5912847538?utm_m...,Software Engineering - Custom Software Engineer,1000000,2700000,5912847538,"{'tag': 'it-jobs', 'label': 'IT Jobs', '__CLAS...","As a Custom Software Engineering Lead, a typic...",eyJhbGciOiJIUzI1NiJ9.eyJzIjoiNUYwejczYkM4UkdfU...,0,78.47879,NaN,NaN
1,12.97060,"{'area': ['India', 'Karnataka', 'Bangalore', '...",2026-10-07T00:04:59Z,Adzuna::API::Response::Job,{'display_name': 'Trigent Software Private Lim...,https://www.adzuna.in/details/5914221304?utm_m...,Software Engineering - Custom Software Engineer,1200000,1650000,5914221304,{'__CLASS__': 'Adzuna::API::Response::Category...,"Skill COBOL Mainframe Mandatory skills-COBOL, ...",eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTkxNDIyMTMwNCIsI...,0,77.60024,NaN,NaN
2,12.97060,{'__CLASS__': 'Adzuna::API::Response::Location...,2026-10-07T00:05:00Z,Adzuna::API::Response::Job,{'display_name': 'Trigent Software Private Lim...,https://www.adzuna.in/details/5914221345?utm_m...,Software Engineering - Custom Software Engineer,1200000,1399992,5914221345,{'__CLASS__': 'Adzuna::API::Response::Category...,Solution Design & ImplementationLead ServiceNo...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTkxNDIyMTM0NSIsI...,0,77.60024,NaN,NaN
3,NaN,"{'display_name': 'India', 'area': ['India'], '...",2026-10-02T07:53:55Z,Adzuna::API::Response::Job,"{'display_name': 'Umanist Staffing LLC', '__CL...",https://www.adzuna.in/details/5906871999?utm_m...,Software Engineer,1500000,1600000,5906871999,{'__CLASS__': 'Adzuna::API::Response::Category...,Backend Engineer In-Office Base location Gurug...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTkwNjg3MTk5OSIsI...,0,NaN,full_time,permanent
4,NaN,{'__CLASS__': 'Adzuna::API::Response::Location...,2026-08-08T06:52:24Z,Adzuna::API::Response::Job,{'__CLASS__': 'Adzuna::API::Response::Company'...,https://www.adzuna.in/details/5832769660?utm_m...,Software Engineer,100000,2000000,5832769660,{'__CLASS__': 'Adzuna::API::Response::Category...,About the Opportunity A fast-scaling tech inno...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiNUYwejczYkM4UkdfU...,0,NaN,full_time,permanent

In [27]:
df.shape

(50, 17)

In [28]:
df.shape

(50, 17)

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   latitude             27 non-null     float64
 1   location             50 non-null     object
 2   created              50 non-null     str
 3   __CLASS__            50 non-null     str
 4   company              50 non-null     object
 5   redirect_url         50 non-null     str
 6   title                50 non-null     str
 7   salary_min           50 non-null     int64
 8   salary_max           50 non-null     int64
 9   id                   50 non-null     object
 10  category             50 non-null     object
 11  description          50 non-null     str
 12  adref                50 non-null     str
 13  salary_is_predicted  50 non-null     str
 14  longitude            27 non-null     float64
 15  contract_time        45 non-null     str
 16  contract_type        2 non-null      str
dtypes: float64(2), int64(2), object(4), str(9)
memory usage: 6.8+ KB

In [30]:
df = pd.DataFrame(salary_jobs)

print(df.shape)
print(df.columns)

df.head()

(50, 17)
Index(['latitude', 'location', 'created', '__CLASS__', 'company',
       'redirect_url', 'title', 'salary_min', 'salary_max', 'id', 'category',
       'description', 'adref', 'salary_is_predicted', 'longitude',
       'contract_time', 'contract_type'],
      dtype='str')

,latitude,location,created,__CLASS__,company,redirect_url,title,salary_min,salary_max,id,category,description,adref,salary_is_predicted,longitude,contract_time,contract_type
0,17.37908,{'__CLASS__': 'Adzuna::API::Response::Location...,2026-10-05T23:54:21Z,Adzuna::API::Response::Job,{'__CLASS__': 'Adzuna::API::Response::Company'...,https://www.adzuna.in/details/5912847538?utm_m...,Software Engineering - Custom Software Engineer,1000000,2700000,5912847538,"{'tag': 'it-jobs', 'label': 'IT Jobs', '__CLAS...","As a Custom Software Engineering Lead, a typic...",eyJhbGciOiJIUzI1NiJ9.eyJzIjoiNUYwejczYkM4UkdfU...,0,78.47879,NaN,NaN
1,12.97060,"{'area': ['India', 'Karnataka', 'Bangalore', '...",2026-10-07T00:04:59Z,Adzuna::API::Response::Job,{'display_name': 'Trigent Software Private Lim...,https://www.adzuna.in/details/5914221304?utm_m...,Software Engineering - Custom Software Engineer,1200000,1650000,5914221304,{'__CLASS__': 'Adzuna::API::Response::Category...,"Skill COBOL Mainframe Mandatory skills-COBOL, ...",eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTkxNDIyMTMwNCIsI...,0,77.60024,NaN,NaN
2,12.97060,{'__CLASS__': 'Adzuna::API::Response::Location...,2026-10-07T00:05:00Z,Adzuna::API::Response::Job,{'display_name': 'Trigent Software Private Lim...,https://www.adzuna.in/details/5914221345?utm_m...,Software Engineering - Custom Software Engineer,1200000,1399992,5914221345,{'__CLASS__': 'Adzuna::API::Response::Category...,Solution Design & ImplementationLead ServiceNo...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTkxNDIyMTM0NSIsI...,0,77.60024,NaN,NaN
3,NaN,"{'display_name': 'India', 'area': ['India'], '...",2026-10-02T07:53:55Z,Adzuna::API::Response::Job,"{'display_name': 'Umanist Staffing LLC', '__CL...",https://www.adzuna.in/details/5906871999?utm_m...,Software Engineer,1500000,1600000,5906871999,{'__CLASS__': 'Adzuna::API::Response::Category...,Backend Engineer In-Office Base location Gurug...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTkwNjg3MTk5OSIsI...,0,NaN,full_time,permanent
4,NaN,{'__CLASS__': 'Adzuna::API::Response::Location...,2026-08-08T06:52:24Z,Adzuna::API::Response::Job,{'__CLASS__': 'Adzuna::API::Response::Company'...,https://www.adzuna.in/details/5832769660?utm_m...,Software Engineer,100000,2000000,5832769660,{'__CLASS__': 'Adzuna::API::Response::Category...,About the Opportunity A fast-scaling tech inno...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiNUYwejczYkM4UkdfU...,0,NaN,full_time,permanent

In [31]:
df = pd.DataFrame(salary_jobs)

print(df.shape)
print(df.columns)

df.head()

(50, 17)
Index(['latitude', 'location', 'created', '__CLASS__', 'company',
       'redirect_url', 'title', 'salary_min', 'salary_max', 'id', 'category',
       'description', 'adref', 'salary_is_predicted', 'longitude',
       'contract_time', 'contract_type'],
      dtype='str')

,latitude,location,created,__CLASS__,company,redirect_url,title,salary_min,salary_max,id,category,description,adref,salary_is_predicted,longitude,contract_time,contract_type
0,17.37908,{'__CLASS__': 'Adzuna::API::Response::Location...,2026-10-05T23:54:21Z,Adzuna::API::Response::Job,{'__CLASS__': 'Adzuna::API::Response::Company'...,https://www.adzuna.in/details/5912847538?utm_m...,Software Engineering - Custom Software Engineer,1000000,2700000,5912847538,"{'tag': 'it-jobs', 'label': 'IT Jobs', '__CLAS...","As a Custom Software Engineering Lead, a typic...",eyJhbGciOiJIUzI1NiJ9.eyJzIjoiNUYwejczYkM4UkdfU...,0,78.47879,NaN,NaN
1,12.97060,"{'area': ['India', 'Karnataka', 'Bangalore', '...",2026-10-07T00:04:59Z,Adzuna::API::Response::Job,{'display_name': 'Trigent Software Private Lim...,https://www.adzuna.in/details/5914221304?utm_m...,Software Engineering - Custom Software Engineer,1200000,1650000,5914221304,{'__CLASS__': 'Adzuna::API::Response::Category...,"Skill COBOL Mainframe Mandatory skills-COBOL, ...",eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTkxNDIyMTMwNCIsI...,0,77.60024,NaN,NaN
2,12.97060,{'__CLASS__': 'Adzuna::API::Response::Location...,2026-10-07T00:05:00Z,Adzuna::API::Response::Job,{'display_name': 'Trigent Software Private Lim...,https://www.adzuna.in/details/5914221345?utm_m...,Software Engineering - Custom Software Engineer,1200000,1399992,5914221345,{'__CLASS__': 'Adzuna::API::Response::Category...,Solution Design & ImplementationLead ServiceNo...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTkxNDIyMTM0NSIsI...,0,77.60024,NaN,NaN
3,NaN,"{'display_name': 'India', 'area': ['India'], '...",2026-10-02T07:53:55Z,Adzuna::API::Response::Job,"{'display_name': 'Umanist Staffing LLC', '__CL...",https://www.adzuna.in/details/5906871999?utm_m...,Software Engineer,1500000,1600000,5906871999,{'__CLASS__': 'Adzuna::API::Response::Category...,Backend Engineer In-Office Base location Gurug...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTkwNjg3MTk5OSIsI...,0,NaN,full_time,permanent
4,NaN,{'__CLASS__': 'Adzuna::API::Response::Location...,2026-08-08T06:52:24Z,Adzuna::API::Response::Job,{'__CLASS__': 'Adzuna::API::Response::Company'...,https://www.adzuna.in/details/5832769660?utm_m...,Software Engineer,100000,2000000,5832769660,{'__CLASS__': 'Adzuna::API::Response::Category...,About the Opportunity A fast-scaling tech inno...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiNUYwejczYkM4UkdfU...,0,NaN,full_time,permanent

In [32]:
print("Number of fields:", len(clean_job))
print()
print(clean_job.keys())

NameError: name 'clean_job' is not defined

In [33]:
print("Number of fields:", len(clean_job))
print()
print(clean_job.keys())

NameError: name 'clean_job' is not defined

In [34]:
x = 10

In [35]:
print(x)

10

In [36]:
job = salary_jobs[0]

In [37]:
clean_job = {
    "job_id": job.get("id"),
    "search_role": "software engineer",
    "title": job.get("title"),
    "company": job.get("company", {}).get("display_name"),
    "location": job.get("location", {}).get("display_name"),
    "category": job.get("category", {}).get("label"),
    "contract_time": job.get("contract_time"),
    "description": job.get("description"),
    "salary_min": job.get("salary_min"),
    "salary_max": job.get("salary_max"),
    "salary_is_predicted": job.get("salary_is_predicted"),
    "created": job.get("created"),
    "redirect_url": job.get("redirect_url")
}

In [38]:
print("Number of fields:", len(clean_job))
print(clean_job.keys())

Number of fields: 13
dict_keys(['job_id', 'search_role', 'title', 'company', 'location', 'category', 'contract_time', 'description', 'salary_min', 'salary_max', 'salary_is_predicted', 'created', 'redirect_url'])

In [39]:
pd.DataFrame([clean_job])

,job_id,search_role,title,company,location,category,contract_time,description,salary_min,salary_max,salary_is_predicted,created,redirect_url
0,5912847538,software engineer,Software Engineering - Custom Software Engineer,Trigent Software Private Limited,"Hussainialam, Hyderabad",IT Jobs,None,"As a Custom Software Engineering Lead, a typic...",1000000,2700000,0,2026-10-05T23:54:21Z,https://www.adzuna.in/details/5912847538?utm_m...

In [40]:
df_test = pd.DataFrame([clean_job])

print("Rows:", df_test.shape[0])
print("Columns:", df_test.shape[1])

Rows: 1
Columns: 13

In [41]:
extract_job(job, search_role)

NameError: name 'extract_job' is not defined

In [43]:
clean_job = {
    "job_id": job.get("id"),
    "title": job.get("title"),
    
}

In [44]:
def extract_job(job, search_role):
    clean_job = {
        "job_id": job.get("id"),
        "search_role": search_role,
        "title": job.get("title"),
        "company": job.get("company", {}).get("display_name"),
        "location": job.get("location", {}).get("display_name"),
        "category": job.get("category", {}).get("label"),
        "contract_time": job.get("contract_time"),
        "description": job.get("description"),
        "salary_min": job.get("salary_min"),
        "salary_max": job.get("salary_max"),
        "salary_is_predicted": job.get("salary_is_predicted"),
        "created": job.get("created"),
        "redirect_url": job.get("redirect_url")
    }

    return clean_job

In [45]:
test_job = extract_job(salary_jobs[0], "software engineer")

test_job

{'job_id': '5912847538',
 'search_role': 'software engineer',
 'title': 'Software Engineering - Custom Software Engineer',
 'company': 'Trigent Software Private Limited',
 'location': 'Hussainialam, Hyderabad',
 'category': 'IT Jobs',
 'contract_time': None,
 'description': 'As a Custom Software Engineering Lead, a typical day involves overseeing the technical vision and architectural framework of bespoke software projects. This role requires guiding teams through the entire lifecycle of design and implementation, ensuring that development practices meet organizational goals. The position demands active involvement in setting standards that promote high-quality, scalable, and efficient software solutions, while fostering collaboration and innovation within the team…',
 'salary_min': 1000000,
 'salary_max': 2700000,
 'salary_is_predicted': '0',
 'created': '2026-10-05T23:54:21Z',
 'redirect_url': 'https://www.adzuna.in/details/5912847538?utm_medium=api&utm_source=de9c063c'}

In [46]:
print(len(test_job))

13

In [47]:
clean_jobs = [
    extract_job(job, "software engineer")
    for job in salary_jobs
]

In [48]:
print(len(clean_jobs))

50

In [49]:
df = pd.DataFrame(clean_jobs)

df.head()

,job_id,search_role,title,company,location,category,contract_time,description,salary_min,salary_max,salary_is_predicted,created,redirect_url
0,5912847538,software engineer,Software Engineering - Custom Software Engineer,Trigent Software Private Limited,"Hussainialam, Hyderabad",IT Jobs,NaN,"As a Custom Software Engineering Lead, a typic...",1000000,2700000,0,2026-10-05T23:54:21Z,https://www.adzuna.in/details/5912847538?utm_m...
1,5914221304,software engineer,Software Engineering - Custom Software Engineer,Trigent Software Private Limited,"Richmond Town, Bangalore",IT Jobs,NaN,"Skill COBOL Mainframe Mandatory skills-COBOL, ...",1200000,1650000,0,2026-10-07T00:04:59Z,https://www.adzuna.in/details/5914221304?utm_m...
2,5914221345,software engineer,Software Engineering - Custom Software Engineer,Trigent Software Private Limited,"Richmond Town, Bangalore",IT Jobs,NaN,Solution Design & ImplementationLead ServiceNo...,1200000,1399992,0,2026-10-07T00:05:00Z,https://www.adzuna.in/details/5914221345?utm_m...
3,5906871999,software engineer,Software Engineer,Umanist Staffing LLC,India,IT Jobs,full_time,Backend Engineer In-Office Base location Gurug...,1500000,1600000,0,2026-10-02T07:53:55Z,https://www.adzuna.in/details/5906871999?utm_m...
4,5832769660,software engineer,Software Engineer,Capawoke,"Bangalore, Karnataka",IT Jobs,full_time,About the Opportunity A fast-scaling tech inno...,100000,2000000,0,2026-08-08T06:52:24Z,https://www.adzuna.in/details/5832769660?utm_m...

In [50]:
df.shape()

TypeError: 'tuple' object is not callable

In [51]:
df.shape

(50, 13)

In [52]:
print("Dataset shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate Job IDs:")
print(df["job_id"].duplicated().sum())

Dataset shape: (50, 13)

Missing values:
job_id                 0
search_role            0
title                  0
company                0
location               0
category               0
contract_time          5
description            0
salary_min             0
salary_max             0
salary_is_predicted    0
created                0
redirect_url           0
dtype: int64

Duplicate Job IDs:
0

In [53]:
print("Dataset shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate Job IDs:")
print(df["job_id"].duplicated().sum())

Dataset shape: (50, 13)

Missing values:
job_id                 0
search_role            0
title                  0
company                0
location               0
category               0
contract_time          5
description            0
salary_min             0
salary_max             0
salary_is_predicted    0
created                0
redirect_url           0
dtype: int64

Duplicate Job IDs:
0

In [54]:
roles = [
    "software engineer",
    "data analyst",
    "data scientist",
    "machine learning engineer",
    "ai engineer",
    "data engineer",
    "backend developer",
    "frontend developer",
    "full stack developer",
    "devops engineer",
    "cloud engineer",
    "cybersecurity analyst"
]

print("Number of roles:", len(roles))

Number of roles: 12

In [55]:
def fetch_jobs(role, page=1, results_per_page=50):

    url = f"https://api.adzuna.com/v1/api/jobs/in/search/{page}"

    params = {
        "app_id": APP_ID,
        "app_key": APP_KEY,
        "results_per_page": results_per_page,
        "what": role,
        "salary_min": 1
    }

    response = requests.get(url, params=params, timeout=30)

    if response.status_code == 200:
        data = response.json()
        return data.get("results", [])

    print(
        f"Request failed for {role}, "
        f"page {page}: {response.status_code}"
    )

    return []

In [56]:
all_jobs = []

pages_per_role = 5

for role in roles:

    print(f"\nCollecting: {role}")

    for page in range(1, pages_per_role + 1):

        jobs = fetch_jobs(role, page)

        print(f"  Page {page}: {len(jobs)} jobs")

        for job in jobs:

            if (
                job.get("salary_min") is not None
                and job.get("salary_max") is not None
                and job.get("salary_is_predicted") == "0"
            ):
                clean_job = extract_job(job, role)
                all_jobs.append(clean_job)

Collecting: software engineer
  Page 1: 50 jobs
Request failed for software engineer, page 2: 503
  Page 2: 0 jobs
  Page 3: 50 jobs
  Page 4: 50 jobs
Request failed for software engineer, page 5: 503
  Page 5: 0 jobs

Collecting: data analyst
  Page 1: 50 jobs
Request failed for data analyst, page 2: 503
  Page 2: 0 jobs
Request failed for data analyst, page 3: 503
  Page 3: 0 jobs
  Page 4: 50 jobs
  Page 5: 50 jobs

Collecting: data scientist
  Page 1: 50 jobs
  Page 2: 50 jobs
Request failed for data scientist, page 3: 503
  Page 3: 0 jobs
  Page 4: 50 jobs
  Page 5: 50 jobs

Collecting: machine learning engineer
Request failed for machine learning engineer, page 1: 503
  Page 1: 0 jobs
  Page 2: 50 jobs
  Page 3: 50 jobs
Request failed for machine learning engineer, page 4: 503
  Page 4: 0 jobs
  Page 5: 29 jobs

Collecting: ai engineer
  Page 1: 50 jobs
  Page 2: 50 jobs
  Page 3: 50 jobs
  Page 4: 50 jobs
  Page 5: 50 jobs

Collecting: data engineer
  Page 1: 50 jobs
  Page 2: 50 jobs
  Page 3: 50 jobs
  Page 4: 50 jobs
  Page 5: 50 jobs

Collecting: backend developer
  Page 1: 50 jobs
  Page 2: 50 jobs
  Page 3: 50 jobs
  Page 4: 50 jobs
Request failed for backend developer, page 5: 503
  Page 5: 0 jobs

Collecting: frontend developer
  Page 1: 50 jobs
  Page 2: 50 jobs
  Page 3: 50 jobs
  Page 4: 50 jobs
  Page 5: 50 jobs

Collecting: full stack developer
  Page 1: 50 jobs
  Page 2: 50 jobs
  Page 3: 50 jobs
  Page 4: 50 jobs
  Page 5: 50 jobs

Collecting: devops engineer
  Page 1: 50 jobs
  Page 2: 50 jobs
  Page 3: 50 jobs
  Page 4: 50 jobs
  Page 5: 50 jobs

Collecting: cloud engineer
  Page 1: 50 jobs
  Page 2: 50 jobs
  Page 3: 50 jobs
  Page 4: 50 jobs
  Page 5: 50 jobs

Collecting: cybersecurity analyst
  Page 1: 5 jobs
  Page 2: 0 jobs
  Page 3: 0 jobs
Request failed for cybersecurity analyst, page 4: 503
  Page 4: 0 jobs
Request failed for cybersecurity analyst, page 5: 503
  Page 5: 0 jobs

In [57]:
jobs_df = pd.DataFrame(all_jobs)

print("Dataset shape:", jobs_df.shape)

jobs_df.head()

Dataset shape: (2334, 13)

,job_id,search_role,title,company,location,category,contract_time,description,salary_min,salary_max,salary_is_predicted,created,redirect_url
0,5912847538,software engineer,Software Engineering - Custom Software Engineer,Trigent Software Private Limited,"Hussainialam, Hyderabad",IT Jobs,NaN,"As a Custom Software Engineering Lead, a typic...",1000000,2700000,0,2026-10-05T23:54:21Z,https://www.adzuna.in/details/5912847538?utm_m...
1,5914221304,software engineer,Software Engineering - Custom Software Engineer,Trigent Software Private Limited,"Richmond Town, Bangalore",IT Jobs,NaN,"Skill COBOL Mainframe Mandatory skills-COBOL, ...",1200000,1650000,0,2026-10-07T00:04:59Z,https://www.adzuna.in/details/5914221304?utm_m...
2,5914221345,software engineer,Software Engineering - Custom Software Engineer,Trigent Software Private Limited,"Richmond Town, Bangalore",IT Jobs,NaN,Solution Design & ImplementationLead ServiceNo...,1200000,1399992,0,2026-10-07T00:05:00Z,https://www.adzuna.in/details/5914221345?utm_m...
3,5906871999,software engineer,Software Engineer,Umanist Staffing LLC,India,IT Jobs,full_time,Backend Engineer In-Office Base location Gurug...,1500000,1600000,0,2026-10-02T07:53:55Z,https://www.adzuna.in/details/5906871999?utm_m...
4,5832769660,software engineer,Software Engineer,Capawoke,"Bangalore, Karnataka",IT Jobs,full_time,About the Opportunity A fast-scaling tech inno...,100000,2000000,0,2026-08-08T06:52:24Z,https://www.adzuna.in/details/5832769660?utm_m...

In [58]:
jobs_df = pd.DataFrame(all_jobs)

print("Dataset shape:", jobs_df.shape)

jobs_df.head()

Dataset shape: (2334, 13)

,job_id,search_role,title,company,location,category,contract_time,description,salary_min,salary_max,salary_is_predicted,created,redirect_url
0,5912847538,software engineer,Software Engineering - Custom Software Engineer,Trigent Software Private Limited,"Hussainialam, Hyderabad",IT Jobs,NaN,"As a Custom Software Engineering Lead, a typic...",1000000,2700000,0,2026-10-05T23:54:21Z,https://www.adzuna.in/details/5912847538?utm_m...
1,5914221304,software engineer,Software Engineering - Custom Software Engineer,Trigent Software Private Limited,"Richmond Town, Bangalore",IT Jobs,NaN,"Skill COBOL Mainframe Mandatory skills-COBOL, ...",1200000,1650000,0,2026-10-07T00:04:59Z,https://www.adzuna.in/details/5914221304?utm_m...
2,5914221345,software engineer,Software Engineering - Custom Software Engineer,Trigent Software Private Limited,"Richmond Town, Bangalore",IT Jobs,NaN,Solution Design & ImplementationLead ServiceNo...,1200000,1399992,0,2026-10-07T00:05:00Z,https://www.adzuna.in/details/5914221345?utm_m...
3,5906871999,software engineer,Software Engineer,Umanist Staffing LLC,India,IT Jobs,full_time,Backend Engineer In-Office Base location Gurug...,1500000,1600000,0,2026-10-02T07:53:55Z,https://www.adzuna.in/details/5906871999?utm_m...
4,5832769660,software engineer,Software Engineer,Capawoke,"Bangalore, Karnataka",IT Jobs,full_time,About the Opportunity A fast-scaling tech inno...,100000,2000000,0,2026-08-08T06:52:24Z,https://www.adzuna.in/details/5832769660?utm_m...

In [59]:
print(
    "Duplicate Job IDs:",
    jobs_df["job_id"].duplicated().sum()
)

Duplicate Job IDs: 65

In [60]:
jobs_df = jobs_df.drop_duplicates(
    subset="job_id",
    keep="first"
).reset_index(drop=True)

In [61]:
print("After removing duplicates:", jobs_df.shape)

After removing duplicates: (2269, 13)

In [62]:
print("After removing duplicates:", jobs_df.shape)

After removing duplicates: (2269, 13)

In [63]:
jobs_df["search_role"].value_counts()

search_role
frontend developer           250
full stack developer         250
devops engineer              248
ai engineer                  243
data engineer                238
cloud engineer               230
backend developer            200
data scientist               192
software engineer            150
data analyst                 150
machine learning engineer    113
cybersecurity analyst          5
Name: count, dtype: int64

In [64]:
jobs_df.to_csv(
    "../data/raw/jobs_raw.csv",
    index=False
)

In [65]:
print("Dataset shape:", df.shape)

Dataset shape: (50, 13)